[package]
name = "olm-rs"
version = "0.2.1"
authors = ["Johannes Hayeß <jhaye@gmx.de>"]

description = "A Rust wrapper for libolm."
license = "GPL-3.0"
readme = "README.md"
repository = "https://gitlab.gnome.org/jhaye/olm-rs"
edition = "2018"

[dependencies]
olm-sys = "0.1.3"
ring = "0.14"

[dev-dependencies]
json = "0.11"
base64 = "0.10"
