[package]
name = "olm-rs"
version = "0.1.0"
authors = ["Johannes Hayeß <jhaye@gmx.de>"]

description = "A Rust wrapper for libolm."
license = "GPL-3"
readme = "README.md"

[dependencies]
olm-sys = "0.1.3"
ring = "0.13"

[dev-dependencies]
json = "0.11"
base64 = "0.9"
